# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f0fae97f6809283c6a8a442fe7b8cefee1ab5c7c548d5a50ce2d2b8faa1bea7e33fc8c26ac3ea41df5c05d8b5a7146de20212e6e9372527f697a62767dd0f8b

test:
  secret_key_base: 315b9d72b2317e10febe443b47c3ee73904be186522b8f4ec604d434e1adc5be6ac8817739e2eb71729368f99ecf9a819aa214968495f45fdb9c541c59c6fb3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
